### ISSUE TITLE
menu under Game needs to be changed or deleted

### ISSUE THREAD

**Issue by sonny87** [zprager/pokerbrain#18]
-If you click on a game , a menu opens up, we have to change the 3 sub buttons to something with sense,

     maybe something like 
                    “quick game”  (sub-line 10 Questions)
                    “xxxxxxxxxx”  (sub-line 25 Questions)
                    “xxxxxxxxxx”  (sub-line 50 Questions)

or we get rid of the menu at all and simply start the game you click on

**Comment by kapilkarda** [comment]
Can you please clearify this things ?

**Comment by sonny87** [comment]
this is actually ok for now, could you please just rename "play a random match" to just "Play !"

**Comment by kapilkarda** [comment]
Done.
