### ISSUE TITLE
ask for Country when signing up 

### ISSUE THREAD

**Issue by sonny87** [zprager/pokerbrain#22]
- we want to use flags for the country in the leaderboards because we will have national leaderboards as well. (i have a confirmation to give away 100x100€ packages for Kings Casino and doesn't make sense to involve US players for example, will only be germans,austrian and italiens)
i think its also fun and more challenging country vs country etc and gives us a better idea where our users are from.

**Comment by kapilkarda** [comment]
okay good idea but I need the database how many country data you want to show.

**Comment by sonny87** [comment]
what exactly do you mean with "how many country data you want to show" ?
i would like that we ask for the country when signing up and that the players have a flag of 
their country after their name in the Leaderboard section only.
the designer is working on leaderboard designs showing a flag as well

**Comment by sonny87** [comment]
could you please also ask for the date of birth when signing up ?
this data will be useful for our marketing later on 
thank you

**Comment by kapilkarda** [comment]
Hello,
I need PSD for all.
Thanks



Kapil Karda,
Email : kkarda77@gmail.com,
Web: http://www.kapilkarda.com

**Comment by kapilkarda** [comment]
Done this changes.

**Comment by sonny87** [comment]
can you make the country and birth data visible in the Admin panel please

**Comment by kapilkarda** [comment]
Done this changes
