### ISSUE TITLE
replace cards with new design and place same directly at the user

### ISSUE THREAD

**Issue by sonny87** [zprager/pokerbrain#23]
could you please replace the cards with the ones in the attached file and also place them like in the attached picture directly at the user and not in the middle of the table.
we created a better design for the cards so that they are more visible on the table in the vertical view.
we also made them thinner to save some space.
thank you

![cards](https://cloud.githubusercontent.com/assets/16062634/12028043/1593def8-add1-11e5-9843-bdaf1bf857ae.jpg)

![12354068_901514636610728_997818309_n 1](https://cloud.githubusercontent.com/assets/16062634/12028046/1bc1fac6-add1-11e5-823b-8b85728536a0.jpg)

**Comment by kapilkarda** [comment]
Hello,
I need PSD for all Images.
Thanks



Kapil Karda,
Email : kkarda77@gmail.com,
Web: http://www.kapilkarda.com

**Comment by kapilkarda** [comment]
Done this changes
