### ISSUE TITLE
My Score Page, wrong Data display

### ISSUE THREAD

**Issue by sonny87** [zprager/pokerbrain#3]
after answering 40 Questions (36 correct) the graphic shows me 4 out of 40,
so it looks like i have 4 out of 40 correct, should say 36 out of 40 and the big part should be green then

also, delete "Orders in" and "Questions answered" text <-- graphic tells everything
also change the pink color in the graphic to the red used for the %position below

**Comment by zprager** [comment]
did you try testing data with new account?

**Comment by sonny87** [comment]
yes

**Comment by kapilkarda** [comment]
I did the changes in last build, please check in the new build
