### ISSUE TITLE
Rename tasks

### ISSUE THREAD

**Issue by sonny87** [zprager/pokerbrain#5]
3) A popup opened up saying "Please try again letter" -should be "later"

already done:
5) if you click "My Topics" and then you see the Games overview, it has a subline saying "Questions"<-- delete that
6) rename app from "better brain" to "PokerBrain"
1)In the side menu rename "Topics" to "Games"
2)same for the Menu thats opening up then saying "My Topics"--> "Games"
4) rename "My Scores" to "My Statistics"

**Comment by kapilkarda** [comment]
Done
